name: Publish templates

on:
  push:
    branches:
    - master
    paths:
    - 'renku/templates/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout renku-python
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: renku-python
    - name: Checkout renku-project-template
      uses: actions/checkout@v2
      with:
        repository: mohammad-sdsc/renku-project-template
        path: renku-project-template
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        cd renku-python
        python -m pip install --upgrade pip
        python -m pip install .[all]
    - name: Commit and create/update pull request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.TEMPLATES_ACCESS_TOKEN }}
        path: renku-project-template
        author: RenkuBot <renku@datascience.ch>
        committer: RenkuBot <renku@datascience.ch>
        commit-message: "Update templates from $(renku --version)"
        title: "Update templates from $(renku --version)"
        body: "Auto-generated PR to publish template changes"
        labels: automerge
        branch: auto-update-templates
